# Generated by Django 4.1 on 2022-08-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_slug_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
