# Generated by Django 4.1 on 2022-08-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Thumbnail",
            new_name="thumbnail",
        ),
    ]
